# Aula - Python

## Fundamentos Básicos

### -----
### 1. Atribuição e impressão na tela
### -----

In [1]:
a = 51;
print(f"Valor de {a}")
a = 5.1
print(f"Valor de {a}")
a = "teste"
print(f"Valor de {a}")
a = 'teste'
print(f"Valor de {a}")

Valor de 51
Valor de 5.1
Valor de teste
Valor de teste


In [2]:
# outro exemplo de print
b = 10
print(f"Valor de {a} {b}")
print("Valor de", a, b)

Valor de teste 10
Valor de teste 10


### -----
### 2. Operações matemáticas básicas
### -----

In [3]:
b = 17
c = 5
print(f"Valor de {c+b}")
print(f"Valor de {c-b}")
print(f"Valor de {c*b}")
print(f"Valor de {b/c}")
print(f"Valor de {round(b/c, ndigits=2)}")
print(f"Valor de {b/c} {b%c}  {b//c}")
print(f"Valor de {4**(0.5)}")

Valor de 22
Valor de -12
Valor de 85
Valor de 3.4
Valor de 3.4
Valor de 3.4 2  3
Valor de 2.0


### -----
### 3. Expressões lógicas
### -----

In [4]:
print(f"Valor de {c == b}")
print(f"Valor de {c > b}")
print(f"Valor de {c >= b}")
print(f"Valor de {c < b}")
print(f"Valor de {c <= b}")
print(f"Valor de {c != b}")
print(f"Valor de {not (c != b)}")

print(f"Valor de {c != b and c < b}")
print(f"Valor de {c != b and c > b}")
print(f"Valor de {c != b or c > b}")

Valor de False
Valor de False
Valor de False
Valor de True
Valor de True
Valor de True
Valor de False
Valor de True
Valor de False
Valor de True


### -----
### 4. if/else
### -----

In [6]:
c = 5
b = 5

if (c > b):
    d = c + b
    print(f"Resultado: {d}")
elif c == b:
    d = c ** b
    print(f"Resultado {d}")
else:
    d = c - b
    print(f"Resultado: {d}")

Resultado 3125


### -----
### 5. Usando bibliotecas do Python
### -----

In [9]:
# biblioteca básica para operações matemáticas
import math as m

print(f"{4**0.5}")
print(f"{m.sqrt(4)}")

2.0
2.0


In [11]:
from math import sqrt as raiz
print(f"{raiz(4)}")

2.0


### -----
### 6. Vetores
### -----

In [20]:
### vetores --> numpy
import numpy as np

v1 = np.zeros(3)
print(v1)

v2 = np.ones(3)
print(v2)

v3 = np.arange(5)
print(v3)

v4 = np.arange(2,5)
print(v4)

v5 = np.repeat("teste", 10)
print(v5)

[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4]
[2 3 4]
['teste' 'teste' 'teste' 'teste' 'teste' 'teste' 'teste' 'teste' 'teste'
 'teste']


In [21]:
# cria um vetor entre 0 e 1 com '0.1 saltos'

np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [10]:
# cria um vetor entre 0 e 10 com incremento de 2
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### -----
### 7. Laços
### -----

In [26]:
# estruturas de controle

for i in v4:
    print(f"Valor: {i}")

Valor: 2
Valor: 3
Valor: 4


In [28]:
for i in np.arange(len(v4)): 
    print(f"Indice: {i} | Valor: {v4[i]}")

Indice: 0 | Valor: 2
Indice: 1 | Valor: 3
Indice: 2 | Valor: 4


In [12]:
[print(i) for i in v3]

0
1
2
3
4


[None, None, None, None, None]

In [30]:
i = 0
while i < len(v4):
    print(v4[i])
    i += 1

2
3
4


### -----
### 8. Funções
### -----

In [36]:
# criação de funções
# usando parametros default
def nova_funcao(a, b=1, c=1):
  return (a+b)*c


In [37]:
print(f"{nova_funcao(5)}")
print(f"{nova_funcao(7,10,7)}")
print(f"{nova_funcao(a = 8, c = 9)}")
print(f"{nova_funcao(a = 7, b = 10, c = 7)}")
#print(f"{nova_funcao(b = 10, c = 7)}")

6
119
81
119


In [19]:
# como verificar a utilização de funções: help

help(print)
# ou
?print

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [40]:
# como importar funções de um arquivo

from teste import *

print(f"{soma(5,6)}")
print(f"{subtrai(5,6)}")

11
-1


### -----
### 9. Matrizes
### -----

In [27]:
# criando matrizes
# a função reshape transforma um vetor (1xT) em uma matriz (M, N)
np.arange(12) #1x12

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
np.arange(12).reshape(4,3) #4x3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
m1 = np.zeros(12).reshape(4,3)
print(m1)

m2 = np.arange(12).reshape(4,3)
print(m2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [30]:
# acessando valores na linha 2 e coluna 2
# lembrem-se que o índice começa do valor 0
m2[2,2]

8

In [48]:
# recuperando apenas a 1a linha
m2[0, :]

array([0, 1, 2])

In [32]:
# recuperando apenas os valores da 1a linha e das 2 primeiras colunas
m2[0, 0:2]

array([0, 1])

In [33]:
# recuperando apenas os valores da 1a coluna
m2[:, 0]

array([0, 3, 6, 9])

In [51]:
print(m1)
print("----")
print(m2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [53]:
# concatenando duas matrizes
m3 = np.append(m1, m2, axis=1)
m3

array([[ 0.,  0.,  0.,  0.,  1.,  2.],
       [ 0.,  0.,  0.,  3.,  4.,  5.],
       [ 0.,  0.,  0.,  6.,  7.,  8.],
       [ 0.,  0.,  0.,  9., 10., 11.]])

In [43]:
print(f"m1 = {m1.shape}")
print(f"m2 = {m2.shape}")
print(f"m3 = {m3.shape}")

m1 = (4, 3)
m2 = (4, 3)
m3 = (8, 3)


### -----
### 13. Salvando em arquivos 
### -----

In [54]:
#salvando em arquivo
np.savetxt("teste.csv", m3, delimiter=",")

In [55]:
#lendo de um arquivo
np.genfromtxt("teste.csv", delimiter=',')

array([[ 0.,  0.,  0.,  0.,  1.,  2.],
       [ 0.,  0.,  0.,  3.,  4.,  5.],
       [ 0.,  0.,  0.,  6.,  7.,  8.],
       [ 0.,  0.,  0.,  9., 10., 11.]])

In [11]:
class robo:
    def __init__(self):
        self.id = ""
    def define_id(self, i):
        self.id = i
    #--Instancia é trazer dp anstratp ára p cpmcretp--
    def mostra_id(self):
        print(self.id)
saulo = robo()
saulo.define_id("Saulo")
saulo.mostra_id()

Saulo


In [2]:
#1. Escreva uma função chamada multiplica que faça multiplicação de dois números
# inteiros utilizando somas.
def multiplica(a, b):
    a_ini = a
    for i in range(b, 1, -1):
        a += a_ini
    return a
print(multiplica(3, 5))

15


In [7]:
# 2. Escreva uma função chamada divide que faça divisão de dois números inteiros
# utilizando subtrações.
def divide(n, d):
    razao = n/d
    for i in range(d, 1, -1):
        n -= razao
    return n
print(divide(25, 5))

5.0


In [9]:
# 3. Escreva uma função chamada potencia que calcule a potência de dois números x
# e y (xy) utilizando multiplicações.
def potencia(a,b):
    a_ini = a
    for i in range(b, 1, -1):
        a *= a_ini
    return a
print(potencia(3, 3))

27


In [15]:
# 4. Escreva uma função chamada primo que recebe um número inteiro e retorne 1, se
# primo, ou 0, caso contrário.
def primo(x):
    if x == 2:
        return True
    elif x%2 == 0:
        return False
    else:
        y = 3
        while y < x:
            if x%y == 0:
                return False
            y += 2
    return True
print(primo(19))

True


In [6]:
# 5. Escreva uma função chamada fatorial que recebe um número e retorne seu
# fatorial.
def fatorial(x):
    x_ini = x
    while x_ini > 1:
        x *= x_ini-1
        x_ini -= 1;
    return x
print(fatorial(10))

3628800


In [10]:
# 6. Escreva uma função chamada inteiros que recebe um número inteiro positivo x e
# retorne a soma de todos os inteiros positivos entre 1 e x.
def inteiros(x):
    i = 2
    soma = 0
    while i < x:
        soma += i
        i += 1
    return soma
print(inteiros(10))

44


In [2]:
# 7. Escreva uma função chamada fibonacci que receba um número e retorne a soma
# da sua sequência de Fibonacci.


In [4]:
# 8. Se listarmos todos os números naturais abaixo de 10 que são múltiplos de 3 ou 5,
# temos 3, 5, 6, 9, cuja soma é 23. Escreva uma função chamada multiplos que recebe
# um número y e retorna a soma de todos os múltiplos de 3 e 5 abaixo desse número y.
def multiplos(x):
    soma = 0
    for i in range(3, x, 1):
        if i%3 == 0 or i%5 == 0:
            soma += i
    return soma
print(multiplos(10))

23


In [6]:
# 9. Escreva uma função chamada menor que recebe um vetor e retorna o menor valor
# dentre os elementos do vetor.
def maior(array):
    maior = array[0]
    for i in array:
        if maior < i:
            maior = i
    return maior
print(maior([1,5,88,10,7,9]))

88


In [8]:
# 10. Escreva uma função chamada menor que recebe um vetor e retorna o maior
# valor dentre os elementos do vetor.
def menor(array):
    menor = array[0]
    for i in array:
        if menor > i:
            menor = i
    return menor
print(menor([1,5,88,10,7,9]))

1


In [10]:
# 11. Escreva uma função chamada media que recebe um vetor e retorna sua
# média.
def media(array):
    soma = 0
    for i in array:
        soma += i
    return soma / len(array)
print(media([1,5,88,10,7,9]))

20.0


In [11]:
# 12. Escreva uma função chamada somamatriz que recebe uma matriz e soma
# todos os elementos da matriz.
def somamatriz(array):
    soma = 0
    for i in range(0, len(array), 1):
        for j in range(0, len(array[i]), 1):
            soma += array[i][j]
    return soma
print(somamatriz([[0, 1, 2, 3], [10, 11, 12, 13]]))

52
